// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/afs/cern.ch/work/c/cquarant/testbeamH4MyRepo/H4Analysis/macros/./AveragePulseShape.C";

#endif
